###########
# site.url, site.title
baseurl: 'http://www.beckyandlukewedding.com'
title: 'Becky &amp; Luke'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

safe: true
lsi: false

